name: C CI

on: [push]

jobs:
    linux:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Install dependencies.
              run: sudo apt-get update && sudo apt-get -qy install libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
            - name: make
              run: make

    mac:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@master
            - name: Install dependencies.
              run: brew install sdl2 sdl2_image sdl2_mixer sdl2_ttf
            - name: make
              run: make

    windows:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@master
            - uses: nuget/setup-nuget@v1
            - name: Install dependencies.
              #run: Get-PackageSource -ProviderName NuGet; Install-Package sdl2.nuget; Install-Package sdl2_image.nuget; Install-Package sdl2_mixer.nuget; Install-Package sdl2_ttf.nuget
              run: dotnet add package sdl2.nuget; dotnet add package sdl2_image.nuget; dotnet add package sdl2_mixer.nuget; dotnet add package sdl2_ttf.nuget
