name: Compiling ...

on: [pull_request, push]

jobs:
    arm32:
        runs-on: ARM32
        steps:
            - uses: actions/checkout@master
            - uses: nuget/setup-nuget@v1
            - uses: ilammy/msvc-dev-cmd@v1

            - name: Install dependencies.
              run: nuget install sdl2.nuget -NonInteractive -ExcludeVersion -OutputDirectory C:\INCLUDE\; nuget install sdl2_image.nuget -NonInteractive -ExcludeVersion -OutputDirectory C:\INCLUDE\; nuget install sdl2_mixer.nuget -NonInteractive -ExcludeVersion -OutputDirectory C:\INCLUDE\; nuget install sdl2_ttf.nuget -NonInteractive -ExcludeVersion -OutputDirectory C:\INCLUDE\
            - name: Install LLVM/clang.
              uses: crazy-max/ghaction-chocolatey@v1
              with:
                  args: install llvm
            - name: Clean up paths to match other platforms.
              run: mkdir C:\INCLUDE\SDL2\; robocopy C:\INCLUDE\sdl2.nuget\build\native\include\ C:\INCLUDE\SDL2\; robocopy C:\INCLUDE\sdl2_image.nuget\build\native\include\ C:\INCLUDE\SDL2\; robocopy C:\INCLUDE\sdl2_mixer.nuget\build\native\include\ C:\INCLUDE\SDL2\; robocopy C:\INCLUDE\sdl2_ttf.nuget\build\native\include\ C:\INCLUDE\SDL2\; if ($LASTEXITCODE -le 7) { exit 0 } else { exit 1 }
            - name: nmake
              run: $Env:CC = "`"C:\Program Files\LLVM\bin\clang.exe`""; nmake /e
            
            - uses: actions/upload-artifact@v1
              with:
                  name: basque_windows_arm32
                  path: basque.exe

    linux:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install dependencies.
              run: sudo apt-get update && sudo apt-get -qy install libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
            - name: make
              run: make
            - uses: actions/upload-artifact@v1
              with:
                  name: basque_linux
                  path: basque

    mac:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install dependencies.
              run: brew install sdl2 sdl2_image sdl2_mixer sdl2_ttf
            - name: make
              run: make
            - uses: actions/upload-artifact@v1
              with:
                  name: basque_mac
                  path: basque

    windows:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@master
            - uses: nuget/setup-nuget@v1
            - uses: ilammy/msvc-dev-cmd@v1

            - name: Install dependencies.
              run: nuget install sdl2.nuget -NonInteractive -ExcludeVersion -OutputDirectory C:\INCLUDE\; nuget install sdl2_image.nuget -NonInteractive -ExcludeVersion -OutputDirectory C:\INCLUDE\; nuget install sdl2_mixer.nuget -NonInteractive -ExcludeVersion -OutputDirectory C:\INCLUDE\; nuget install sdl2_ttf.nuget -NonInteractive -ExcludeVersion -OutputDirectory C:\INCLUDE\
            - name: Install LLVM/clang.
              uses: crazy-max/ghaction-chocolatey@v1
              with:
                  args: install llvm
            - name: Clean up paths to match other platforms.
              run: mkdir C:\INCLUDE\SDL2\; robocopy C:\INCLUDE\sdl2.nuget\build\native\include\ C:\INCLUDE\SDL2\; robocopy C:\INCLUDE\sdl2_image.nuget\build\native\include\ C:\INCLUDE\SDL2\; robocopy C:\INCLUDE\sdl2_mixer.nuget\build\native\include\ C:\INCLUDE\SDL2\; robocopy C:\INCLUDE\sdl2_ttf.nuget\build\native\include\ C:\INCLUDE\SDL2\; if ($LASTEXITCODE -le 7) { exit 0 } else { exit 1 }
            - name: nmake
              run: $Env:CC = "`"C:\Program Files\LLVM\bin\clang.exe`""; nmake /e
            
            - uses: actions/upload-artifact@v1
              with:
                  name: basque_windows
                  path: basque.exe
