name: C CI

on: [push]

jobs:
    linux:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies.
              run: sudo apt-get update && sudo apt-get -qy install libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
            - name: make
              run: make

    mac:

        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies.
              run: brew install sdl2 sdl2_image sdl2_mixer sdl2_ttf
            - name: make
              run: make
